name:                poda
version:             0.1.0.0
github:              "githubuser/poda"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/poda#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- cassava

ghc-options:
- -Wall

default-extensions:
- OverloadedStrings

library:
  source-dirs: src
  dependencies:
  - ascii-progress
  - async
  - containers
  - http-client
  - http-client-tls
  - http-types
  - matplotlib
  - mtl
  - persistent
  - persistent-sqlite
  - text
  - time
  - unicode-show
  - unordered-containers

executables:
  poda:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - poda
    - directory
    - filepath
    - text
    - time

tests:
  poda-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - poda
    - containers
    - hspec
    - persistent
    - persistent-sqlite
    - raw-strings-qq
    - text
    - time
    - unordered-containers
